version: '2'
services:
  fuelmock-app:
    image: fuelmock
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fuelmock-postgresql:5432/fuelmock
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  fuelmock-postgresql:
    extends:
      file: postgresql.yml
      service: fuelmock-postgresql
